package com.example.task_frontend_mira_morning_mobile

object Routes {
    var BerandaBody = "BerandaBody"
    var ListBuku = "ListBuku"
    var Koleksi = "Koleksi"
    var About = "About"
    var ScreenBeranda = "ScreenBeranda"
    var ScreenListBuku = "ScreenBuku"
    var ScreenKoleksi = "ScreenKoleksi"
    var ScreenAbout = "ScreenAbout"
    var Detail20Holistic = "Detail20Holistic"
    var DetailAngkot = "DetailAngkot"
    var DetailBuyaHamka = "DetailBuyaHamka"
    var DetailCahayaHutan = "DetailCahayaHutan"
    var DetailCounsels = "DetailCounsels"
    var DetailDeepNutrision = "DetailDeepNutrision"
    var DetailDeepDepression = " DetailDeepDepression"
    var DetailDhirga = "DetailDhirga"
    var DetailFiksiImperfect = "DetailFiksiImperfect"
    var DetailFiksiPergi = "DetailFiksiPergi"
    var DetailHellHouse = "DetailHellHouse"
    var DetailJiwaNegarawan = "DetailJiwaNegarawan"
    var DetailKamus = "DetailKamus"
    var DetailKartini = "DetailKartini"
    var DetailNelsonMandela = " DetailNelsonMandela"
    var DetailPanglima = "DetailPanglima"
    var DetailPenghantarIlmuHukum = "DetailPenghantarIlmuHukum"
    var DetailPuisiCinta = "DetailPuisiCinta"
    var DetailPulang = "DetailPulang"
    var DetailRindu = "DetailRindu"
    var DetailSalamTerakhir = "DetailSalamTerakhir"
    var DetailSantri = "DetailSantri"
    var DetailSapiens = "DetailSapiens"
    var DetailSiJuki = "DetailSiJuki"
    var DetailSoeharto = "DetailSoeharto"
    var DetailSpacedum = "DetailSpacedum"
    var DetailThoseEyes = "DetailThoseEyes"
    var DetailTotalHealth = "DetailTotalHealth"


}